### ISSUE TITLE
Unreadable Texts in Website Pages

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/club-website-2019#28]
Text is unreadable in many pages of the main website  -
![image](https://user-images.githubusercontent.com/21276922/70835177-48f5a180-1e22-11ea-85ee-c57ce877bd78.png)
![image](https://user-images.githubusercontent.com/21276922/70835363-dd600400-1e22-11ea-946c-b2441d8bf884.png)

Due to #26 getting merged, I see the background set in body attribute of ``src/components/events/hacktoberfest/styles/style.sass`` getting applied globally. Since Gatsby bundles sass together, though unrelated, these get applied to the main site as well.

**Comment by vibhoothi** [comment]
Hope this is fixed,

We tested and I think it is now fixed
