### ISSUE TITLE
Incorrect Data displayed in Footer

### ISSUE THREAD

**Issue by vibhoothi** [amfoss/club-website-2019#3]
Hi,

In the website footer, its showing like this 
<img width="333" alt="Screenshot 2019-05-28 at 1 21 42 AM" src="https://user-images.githubusercontent.com/10833993/58437340-22bb1f00-80e7-11e9-96af-e5b2b8c728e7.png">
Its in `component/theme/footer-nav.js`
https://github.com/amfoss/website/blob/f3a3e1bc95cc404eefd5db79b0c27d6655b4fe9d/src/components/theme/footer-nav.js#L94
Which should be replaced with 
`#amfoss` on Freenode. Join via [Freenode Webchat](https://webchat.freenode.net/?channels=amfoss) or use your favourite IRC client.

**Comment by harshithpabbati** [comment]
Thanks, @vibhoothiiaanand will update it :)

**Comment by aswinshenoy** [comment]
@vibhoothiiaanand thank you, fixed.
